language: r
dist: trusty
sudo: false
cache: packages

r:
 - 3.2
 - oldrel
 - release
 - devel

after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'

env:
  global:
  - NOT_CRAN=true
  - secure: "AkQ6xzik9zlMPWo6Y/XH0IJF/0EHQSYKADAFmnawpp9MNUj+chaASM+ZtcY80MgMw3yeyiEvC8RnUTvL0QMXk++MclQuwRycu8WB5dMoIuVKqFfaSVrXX50vRG4/fesohvTCX1UlzhF45Kb6OgWzgzJ5yjVnO85PI/nxdp+nxDoLhofZNj4srdbYTXtO2tBoR9Y48vsj3HAAqtxqAbEefQTw+Tt5bQYJbyxOFaHPyFzRVpJeAhEISAWqRxGnuPouoRTOGzeR72EWx6v8dCF08V5vUKeztZc+LeR9p93SVZPqNLhjvXWFWfPnRrCGR6cID41vr2hq1z4jwKfXxMrPiQ2I0mpH2W+FSICjraNgcm6zXBvbqCxCM4sUuHtwEQ3ARdngyAYkFm1I8IGTv3lkm97DEJbSfXeIis8NOnkMbmcNiNWXFny/hhWBhb2W5+zQYo1flXLj5Tpac1fEFrMKoRQfGB5sh3rlpvD5UJp/Kab1m4pVCJaM0oEzIMsV1h32wLhABGDhq4YzPl0h1h6OwdRAESVQWV+CprXxmuDOZhPo8ppe0aLlQCT4THf4+tnuUkEvVjzuJTCKGm9S8ezGG2+LCkVFYoVwJ9HBdAw0Y413j214Sn6cFha28RjonGKO2CVNhacIe7O76rohWO74hIqjhDcjLLUsaFy0y0+iM9I="
